/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import VglutHomerTools.Vglut_Homer_Tools3D;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;


/**
 *
 * @author phm
 */
public class JDialogParametersVglut_Homer_Astro extends javax.swing.JDialog {

    Vglut_Homer_Tools3D astro = null;
    String[] chs = astro.channels.toArray(new String[astro.channels.size()]);
    NumberFormat nf = NumberFormat.getNumberInstance(Locale.US);
    NumberFormatter nff = new NumberFormatter(nf);
    
    /**
     * Creates new form SegmentationJDialog
     */
    public JDialogParametersVglut_Homer_Astro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //System.out.println(info.getName()+" ");
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogParametersVglut_Homer_Astro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        initComponents();
        astro = Vglut_Homer_Tools3D.instance;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelChannels = new javax.swing.JPanel();
        jLabelAstroCh = new javax.swing.JLabel();
        jComboBoxAstroCh = new javax.swing.JComboBox(chs);
        jComboBoxVglutConfCh = new javax.swing.JComboBox(chs);
        jLabelVglutConfh = new javax.swing.JLabel();
        jLabelVglutStedCh = new javax.swing.JLabel();
        jComboBoxVglutStedCh = new javax.swing.JComboBox(chs);
        jLabel5 = new javax.swing.JLabel();
        jLabelHomerConfCh = new javax.swing.JLabel();
        jComboBoxHomerConfCh = new javax.swing.JComboBox(chs);
        jComboBoxHomerStedCh = new javax.swing.JComboBox(chs);
        jLabelHomerStedCh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelVglut = new javax.swing.JPanel();
        jLabelVglutParams = new javax.swing.JLabel();
        jLabelVglutrMaxParams = new javax.swing.JLabel();
        jLabelVglutRadXY = new javax.swing.JLabel();
        jFormattedTextFieldVglutRadXY = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance(Locale.ENGLISH));
        jLabelVglutRadZ = new javax.swing.JLabel();
        jFormattedTextFieldVglutRadZ = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance(Locale.ENGLISH));
        jLabelVglutNoise = new javax.swing.JLabel();
        jFormattedTextFieldVglutNoise = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldVglutConfIntRef = new javax.swing.JFormattedTextField();
        jPanelHomer = new javax.swing.JPanel();
        jLabelHomerParams = new javax.swing.JLabel();
        jLabelHomerMaxParams = new javax.swing.JLabel();
        jFormattedTextFieldHomerRadXY = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance(Locale.ENGLISH));
        jLabelHomerRadXY = new javax.swing.JLabel();
        jLabelHomerRadZ = new javax.swing.JLabel();
        jFormattedTextFieldHomerRadZ = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance(Locale.ENGLISH));
        ;
        jLabelHomerNoise = new javax.swing.JLabel();
        jFormattedTextFieldHomerNoise = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldHomerConfIntRef = new javax.swing.JFormattedTextField();
        jPanelSynapse = new javax.swing.JPanel();
        jCheckBoxBleachAstro = new javax.swing.JCheckBox();
        jLabelMaxDistSynap = new javax.swing.JLabel();
        jFormattedTextFieldMaxDotsDist = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelMaxDistAstro = new javax.swing.JLabel();
        jFormattedTextFieldMaxDistAstro = new javax.swing.JFormattedTextField();
        jLabelAstroBleach = new javax.swing.JLabel();
        jLabelVglutConfBleach = new javax.swing.JLabel();
        jLabelVglutStedBleach = new javax.swing.JLabel();
        jLabelHomerConfBleach = new javax.swing.JLabel();
        jLabelHomerStedBleach = new javax.swing.JLabel();
        jCheckBoxBleachVglutConf = new javax.swing.JCheckBox();
        jCheckBoxBleachVglutSted = new javax.swing.JCheckBox();
        jCheckBoxBleachHomerConf = new javax.swing.JCheckBox();
        jCheckBoxBleachHomerSted = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Segmentation parameters");
        setForeground(new java.awt.Color(51, 51, 51));
        setModal(true);

        jButtonOk.setForeground(java.awt.Color.black);
        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setForeground(java.awt.Color.black);
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jTabbedPane1.setForeground(java.awt.Color.lightGray);

        jLabelAstroCh.setForeground(java.awt.Color.black);
        jLabelAstroCh.setText("Astrocyte channel  :");

        jComboBoxAstroCh.setForeground(java.awt.Color.black);
        jComboBoxAstroCh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAstroChItemStateChanged(evt);
            }
        });

        jComboBoxVglutConfCh.setForeground(java.awt.Color.black);
        jComboBoxVglutConfCh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxVglutConfChItemStateChanged(evt);
            }
        });

        jLabelVglutConfh.setForeground(java.awt.Color.black);
        jLabelVglutConfh.setText("Vglut confocal channel :");

        jLabelVglutStedCh.setForeground(java.awt.Color.black);
        jLabelVglutStedCh.setText("Vglut Sted channel :");

        jComboBoxVglutStedCh.setForeground(java.awt.Color.black);
        jComboBoxVglutStedCh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxVglutStedChItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Channels parameters");

        jLabelHomerConfCh.setForeground(java.awt.Color.black);
        jLabelHomerConfCh.setText("Homer confocal channel :");

        jComboBoxHomerConfCh.setForeground(java.awt.Color.black);
        jComboBoxHomerConfCh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxHomerConfChItemStateChanged(evt);
            }
        });

        jComboBoxHomerStedCh.setForeground(java.awt.Color.black);
        jComboBoxHomerStedCh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxHomerStedChItemStateChanged(evt);
            }
        });

        jLabelHomerStedCh.setForeground(java.awt.Color.black);
        jLabelHomerStedCh.setText("Homer Sted channel :");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Orion_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanelChannelsLayout = new javax.swing.GroupLayout(jPanelChannels);
        jPanelChannels.setLayout(jPanelChannelsLayout);
        jPanelChannelsLayout.setHorizontalGroup(
            jPanelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChannelsLayout.createSequentialGroup()
                .addGroup(jPanelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChannelsLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAstroCh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelVglutConfh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelVglutStedCh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHomerConfCh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHomerStedCh, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxVglutConfCh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxVglutStedCh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxAstroCh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxHomerConfCh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxHomerStedCh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelChannelsLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(jPanelChannelsLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanelChannelsLayout.setVerticalGroup(
            jPanelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChannelsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAstroCh)
                    .addComponent(jComboBoxAstroCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVglutConfh)
                    .addComponent(jComboBoxVglutConfCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVglutStedCh)
                    .addComponent(jComboBoxVglutStedCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHomerConfCh)
                    .addComponent(jComboBoxHomerConfCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHomerStedCh)
                    .addComponent(jComboBoxHomerStedCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jComboBoxAstroCh.setModel(new DefaultComboBoxModel<>(chs));
        jComboBoxAstroCh.setSelectedItem("0");
        jComboBoxVglutConfCh.setModel(new DefaultComboBoxModel<>(chs));
        jComboBoxVglutConfCh.setSelectedItem("1");
        jComboBoxVglutStedCh.setModel(new DefaultComboBoxModel<>(chs));
        jComboBoxVglutStedCh.setSelectedItem("2");
        jComboBoxHomerConfCh.setModel(new DefaultComboBoxModel<>(chs));
        jComboBoxHomerConfCh.setSelectedItem("3");
        jComboBoxHomerStedCh.setModel(new DefaultComboBoxModel<>(chs));
        jComboBoxHomerStedCh.setSelectedItem("4");

        jTabbedPane1.addTab("Channels", jPanelChannels);

        jLabelVglutParams.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabelVglutParams.setForeground(java.awt.Color.green);
        jLabelVglutParams.setText("Vglut dots parameters");

        jLabelVglutrMaxParams.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabelVglutrMaxParams.setForeground(java.awt.Color.black);
        jLabelVglutrMaxParams.setText("3D maxima finder");

        jLabelVglutRadXY.setForeground(java.awt.Color.black);
        jLabelVglutRadXY.setText("Radius XY (pixel) :");

        jFormattedTextFieldVglutRadXY.setForeground(java.awt.Color.black);
        jFormattedTextFieldVglutRadXY.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldVglutRadXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldVglutRadXYActionPerformed(evt);
            }
        });
        jFormattedTextFieldVglutRadXY.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextFieldVglutRadXYPropertyChange(evt);
            }
        });

        jLabelVglutRadZ.setForeground(java.awt.Color.black);
        jLabelVglutRadZ.setText("Radius Z (pixel) :");

        jFormattedTextFieldVglutRadZ.setForeground(java.awt.Color.black);
        jFormattedTextFieldVglutRadZ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldVglutRadZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldVglutRadZActionPerformed(evt);
            }
        });
        jFormattedTextFieldVglutRadZ.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextFieldVglutRadZPropertyChange(evt);
            }
        });

        jLabelVglutNoise.setForeground(java.awt.Color.black);
        jLabelVglutNoise.setText("Noise :");

        jFormattedTextFieldVglutNoise.setForeground(java.awt.Color.black);
        jFormattedTextFieldVglutNoise.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldVglutNoise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldVglutNoiseActionPerformed(evt);
            }
        });
        jFormattedTextFieldVglutNoise.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextFieldVglutNoisePropertyChange(evt);
            }
        });

        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Confocal channel reference intensity  :");

        jFormattedTextFieldVglutConfIntRef.setForeground(java.awt.Color.black);
        jFormattedTextFieldVglutConfIntRef.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldVglutConfIntRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldVglutConfIntRefActionPerformed(evt);
            }
        });
        jFormattedTextFieldVglutConfIntRef.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextFieldVglutConfIntRefPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanelVglutLayout = new javax.swing.GroupLayout(jPanelVglut);
        jPanelVglut.setLayout(jPanelVglutLayout);
        jPanelVglutLayout.setHorizontalGroup(
            jPanelVglutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVglutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVglutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVglutLayout.createSequentialGroup()
                        .addGroup(jPanelVglutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVglutNoise, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelVglutRadZ, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelVglutRadXY, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVglutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelVglutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFormattedTextFieldVglutRadZ, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldVglutRadXY))
                            .addComponent(jFormattedTextFieldVglutNoise, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelVglutrMaxParams)
                    .addComponent(jLabelVglutParams)
                    .addGroup(jPanelVglutLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(jFormattedTextFieldVglutConfIntRef, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanelVglutLayout.setVerticalGroup(
            jPanelVglutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVglutLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelVglutParams)
                .addGap(18, 18, 18)
                .addGroup(jPanelVglutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldVglutConfIntRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelVglutrMaxParams)
                .addGap(18, 18, 18)
                .addGroup(jPanelVglutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldVglutRadXY, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVglutRadXY))
                .addGap(18, 18, 18)
                .addGroup(jPanelVglutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVglutRadZ)
                    .addComponent(jFormattedTextFieldVglutRadZ, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelVglutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVglutNoise)
                    .addComponent(jFormattedTextFieldVglutNoise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jFormattedTextFieldVglutRadXY.setValue(astro.vglutMaxRadXY);
        jFormattedTextFieldVglutRadZ.setValue(astro.vglutMaxRadZ);
        jFormattedTextFieldVglutNoise.setValue(astro.vglutNoise);
        jFormattedTextFieldVglutConfIntRef.setValue(astro.vglutConfDotsIntRef);

        jTabbedPane1.addTab("Vglut", jPanelVglut);

        jLabelHomerParams.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabelHomerParams.setForeground(java.awt.Color.red);
        jLabelHomerParams.setText("Homer dots parameters");

        jLabelHomerMaxParams.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabelHomerMaxParams.setForeground(java.awt.Color.black);
        jLabelHomerMaxParams.setText("3D maxima finder");

        jFormattedTextFieldHomerRadXY.setForeground(java.awt.Color.black);
        jFormattedTextFieldHomerRadXY.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldHomerRadXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldHomerRadXYActionPerformed(evt);
            }
        });
        jFormattedTextFieldHomerRadXY.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextFieldHomerRadXYPropertyChange(evt);
            }
        });

        jLabelHomerRadXY.setForeground(java.awt.Color.black);
        jLabelHomerRadXY.setText("Radius XY (pixel) :");

        jLabelHomerRadZ.setForeground(java.awt.Color.black);
        jLabelHomerRadZ.setText("Radius Z (pixel) :");

        jFormattedTextFieldHomerRadZ.setForeground(java.awt.Color.black);
        jFormattedTextFieldHomerRadZ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldHomerRadZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldHomerRadZActionPerformed(evt);
            }
        });
        jFormattedTextFieldHomerRadZ.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextFieldHomerRadZPropertyChange(evt);
            }
        });

        jLabelHomerNoise.setForeground(java.awt.Color.black);
        jLabelHomerNoise.setText("Noise :");

        jFormattedTextFieldHomerNoise.setForeground(java.awt.Color.black);
        jFormattedTextFieldHomerNoise.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldHomerNoise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldHomerNoiseActionPerformed(evt);
            }
        });
        jFormattedTextFieldHomerNoise.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextFieldHomerNoisePropertyChange(evt);
            }
        });

        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Confocal channel reference intensity  :");

        jFormattedTextFieldHomerConfIntRef.setForeground(java.awt.Color.black);
        jFormattedTextFieldHomerConfIntRef.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldHomerConfIntRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldHomerConfIntRefActionPerformed(evt);
            }
        });
        jFormattedTextFieldHomerConfIntRef.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextFieldHomerConfIntRefPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanelHomerLayout = new javax.swing.GroupLayout(jPanelHomer);
        jPanelHomer.setLayout(jPanelHomerLayout);
        jPanelHomerLayout.setHorizontalGroup(
            jPanelHomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomerLayout.createSequentialGroup()
                        .addGroup(jPanelHomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHomerRadXY, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHomerRadZ, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHomerNoise, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelHomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelHomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFormattedTextFieldHomerRadZ, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldHomerRadXY))
                            .addComponent(jFormattedTextFieldHomerNoise, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelHomerMaxParams)
                    .addComponent(jLabelHomerParams)
                    .addGroup(jPanelHomerLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(jFormattedTextFieldHomerConfIntRef, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanelHomerLayout.setVerticalGroup(
            jPanelHomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelHomerParams)
                .addGap(18, 18, 18)
                .addGroup(jPanelHomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldHomerConfIntRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelHomerMaxParams)
                .addGap(18, 18, 18)
                .addGroup(jPanelHomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldHomerRadXY, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHomerRadXY))
                .addGap(18, 18, 18)
                .addGroup(jPanelHomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHomerRadZ)
                    .addComponent(jFormattedTextFieldHomerRadZ, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelHomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHomerNoise)
                    .addComponent(jFormattedTextFieldHomerNoise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jFormattedTextFieldHomerRadXY.setValue(astro.homerMaxRadXY);
        jFormattedTextFieldHomerRadZ.setValue(astro.homerMaxRadZ);
        jFormattedTextFieldHomerNoise.setValue(astro.homerNoise);
        jFormattedTextFieldHomerConfIntRef.setValue(astro.homerConfDotsIntRef);

        jTabbedPane1.addTab("Homer", jPanelHomer);

        jCheckBoxBleachAstro.setForeground(java.awt.Color.black);
        jCheckBoxBleachAstro.setText("enable");
        jCheckBoxBleachAstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBleachAstroActionPerformed(evt);
            }
        });

        jLabelMaxDistSynap.setForeground(java.awt.Color.black);
        jLabelMaxDistSynap.setText("Maximum distance between 2 dots (micron) :");
        jLabelMaxDistSynap.setToolTipText("maximun distance between 2 dots to define a synapse");

        jFormattedTextFieldMaxDotsDist.setForeground(java.awt.Color.black);
        jFormattedTextFieldMaxDotsDist.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFormattedTextFieldMaxDotsDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldMaxDotsDistActionPerformed(evt);
            }
        });
        jFormattedTextFieldMaxDotsDist.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextFieldMaxDotsDistPropertyChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Histogram matching bleach correction");

        jLabel4.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Synapse parameters");

        jLabelMaxDistAstro.setForeground(java.awt.Color.black);
        jLabelMaxDistAstro.setText("Maximum distance to astrocyte (micron) :");
        jLabelMaxDistAstro.setToolTipText("Astrocyte maximum distance to keep a synapse");

        jFormattedTextFieldMaxDistAstro.setForeground(java.awt.Color.black);
        jFormattedTextFieldMaxDistAstro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFormattedTextFieldMaxDistAstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldMaxDistAstroActionPerformed(evt);
            }
        });
        jFormattedTextFieldMaxDistAstro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextFieldMaxDistAstroPropertyChange(evt);
            }
        });

        jLabelAstroBleach.setForeground(java.awt.Color.black);
        jLabelAstroBleach.setText("Astrocyte channel  :");

        jLabelVglutConfBleach.setForeground(java.awt.Color.black);
        jLabelVglutConfBleach.setText("Vglut confocal channel :");

        jLabelVglutStedBleach.setForeground(java.awt.Color.black);
        jLabelVglutStedBleach.setText("Vglut Sted channel :");

        jLabelHomerConfBleach.setForeground(java.awt.Color.black);
        jLabelHomerConfBleach.setText("Homer confocal channel :");

        jLabelHomerStedBleach.setForeground(java.awt.Color.black);
        jLabelHomerStedBleach.setText("Homer Sted channel :");

        jCheckBoxBleachVglutConf.setForeground(java.awt.Color.black);
        jCheckBoxBleachVglutConf.setText("enable");
        jCheckBoxBleachVglutConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBleachVglutConfActionPerformed(evt);
            }
        });

        jCheckBoxBleachVglutSted.setForeground(java.awt.Color.black);
        jCheckBoxBleachVglutSted.setText("enable");
        jCheckBoxBleachVglutSted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBleachVglutStedActionPerformed(evt);
            }
        });

        jCheckBoxBleachHomerConf.setForeground(java.awt.Color.black);
        jCheckBoxBleachHomerConf.setText("enable");
        jCheckBoxBleachHomerConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBleachHomerConfActionPerformed(evt);
            }
        });

        jCheckBoxBleachHomerSted.setForeground(java.awt.Color.black);
        jCheckBoxBleachHomerSted.setText("enable");
        jCheckBoxBleachHomerSted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBleachHomerStedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSynapseLayout = new javax.swing.GroupLayout(jPanelSynapse);
        jPanelSynapse.setLayout(jPanelSynapseLayout);
        jPanelSynapseLayout.setHorizontalGroup(
            jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSynapseLayout.createSequentialGroup()
                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSynapseLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSynapseLayout.createSequentialGroup()
                                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMaxDistAstro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMaxDistSynap, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldMaxDotsDist, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldMaxDistAstro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelSynapseLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAstroBleach, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelVglutConfBleach, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelVglutStedBleach, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelHomerConfBleach, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelHomerStedBleach, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxBleachAstro)
                                    .addComponent(jCheckBoxBleachVglutConf)
                                    .addComponent(jCheckBoxBleachVglutSted)
                                    .addComponent(jCheckBoxBleachHomerConf)
                                    .addComponent(jCheckBoxBleachHomerSted)))
                            .addComponent(jLabel3)))
                    .addGroup(jPanelSynapseLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelSynapseLayout.setVerticalGroup(
            jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSynapseLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaxDistSynap)
                    .addComponent(jFormattedTextFieldMaxDotsDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaxDistAstro)
                    .addComponent(jFormattedTextFieldMaxDistAstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAstroBleach)
                    .addComponent(jCheckBoxBleachAstro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxBleachVglutConf)
                    .addComponent(jLabelVglutConfBleach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxBleachVglutSted)
                    .addComponent(jLabelVglutStedBleach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxBleachHomerConf)
                    .addComponent(jLabelHomerConfBleach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSynapseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxBleachHomerSted)
                    .addComponent(jLabelHomerStedBleach))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jFormattedTextFieldMaxDotsDist.setValue(astro.maxDistSynap);
        jFormattedTextFieldMaxDotsDist.setFormatterFactory(new DefaultFormatterFactory(nff));
        jFormattedTextFieldMaxDistAstro.setValue(astro.maxDistAstro);
        jFormattedTextFieldMaxDistAstro.setFormatterFactory(new DefaultFormatterFactory(nff));

        jTabbedPane1.addTab("Synapses", jPanelSynapse);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        this.dispose();
        astro = Vglut_Homer_Tools3D.instance;
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
        astro.channels = null;
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jComboBoxAstroChItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAstroChItemStateChanged
        // TODO add your handling code here:
        astro.channels.add(0, jComboBoxAstroCh.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxAstroChItemStateChanged

    private void jComboBoxVglutConfChItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxVglutConfChItemStateChanged
        // TODO add your handling code here:
        astro.channels.add(1, jComboBoxVglutConfCh.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxVglutConfChItemStateChanged

    private void jComboBoxVglutStedChItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxVglutStedChItemStateChanged
        // TODO add your handling code here:
        astro.channels.add(2, jComboBoxVglutStedCh.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxVglutStedChItemStateChanged

    private void jFormattedTextFieldHomerRadXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHomerRadXYActionPerformed
        // TODO add your handling code here:
        astro.homerMaxRadXY = ((Number)jFormattedTextFieldHomerRadXY.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldHomerRadXYActionPerformed

    private void jFormattedTextFieldHomerRadZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHomerRadZActionPerformed
        // TODO add your handling code here:
         astro.homerMaxRadZ = ((Number)jFormattedTextFieldHomerRadZ.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldHomerRadZActionPerformed

    private void jFormattedTextFieldHomerNoiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHomerNoiseActionPerformed
        // TODO add your handling code here:
        astro.homerNoise = ((Number)jFormattedTextFieldHomerNoise.getValue()).intValue();
    }//GEN-LAST:event_jFormattedTextFieldHomerNoiseActionPerformed

    private void jFormattedTextFieldVglutRadXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldVglutRadXYActionPerformed
        // TODO add your handling code here:
        astro.vglutMaxRadXY = ((Number)jFormattedTextFieldVglutRadXY.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldVglutRadXYActionPerformed

    private void jFormattedTextFieldVglutRadZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldVglutRadZActionPerformed
        // TODO add your handling code here:
        astro.vglutMaxRadZ = ((Number)jFormattedTextFieldVglutRadZ.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldVglutRadZActionPerformed

    private void jFormattedTextFieldVglutNoiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldVglutNoiseActionPerformed
        // TODO add your handling code here:
        astro.vglutNoise = ((Number)jFormattedTextFieldVglutNoise.getValue()).intValue();
    }//GEN-LAST:event_jFormattedTextFieldVglutNoiseActionPerformed

    private void jComboBoxHomerConfChItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxHomerConfChItemStateChanged
        // TODO add your handling code here:
        astro.channels.add(3, jComboBoxHomerConfCh.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxHomerConfChItemStateChanged

    private void jComboBoxHomerStedChItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxHomerStedChItemStateChanged
        // TODO add your handling code here:
        astro.channels.add(4, jComboBoxHomerStedCh.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxHomerStedChItemStateChanged

    private void jFormattedTextFieldVglutConfIntRefPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextFieldVglutConfIntRefPropertyChange
        // TODO add your handling code here:
        astro.vglutConfDotsIntRef = ((Number)jFormattedTextFieldVglutConfIntRef.getValue()).intValue();
    }//GEN-LAST:event_jFormattedTextFieldVglutConfIntRefPropertyChange

    private void jFormattedTextFieldVglutConfIntRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldVglutConfIntRefActionPerformed
        // TODO add your handling code here:
        astro.vglutConfDotsIntRef = ((Number)jFormattedTextFieldVglutConfIntRef.getValue()).intValue();
    }//GEN-LAST:event_jFormattedTextFieldVglutConfIntRefActionPerformed

    private void jFormattedTextFieldVglutRadXYPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextFieldVglutRadXYPropertyChange
        // TODO add your handling code here:
        astro.vglutMaxRadXY = ((Number)jFormattedTextFieldVglutRadXY.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldVglutRadXYPropertyChange

    private void jFormattedTextFieldVglutRadZPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextFieldVglutRadZPropertyChange
        // TODO add your handling code here:
        astro.vglutMaxRadZ = ((Number)jFormattedTextFieldVglutRadZ.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldVglutRadZPropertyChange

    private void jFormattedTextFieldVglutNoisePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextFieldVglutNoisePropertyChange
        // TODO add your handling code here:
        astro.vglutNoise = ((Number)jFormattedTextFieldVglutNoise.getValue()).intValue();
    }//GEN-LAST:event_jFormattedTextFieldVglutNoisePropertyChange

    private void jFormattedTextFieldHomerRadXYPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHomerRadXYPropertyChange
        // TODO add your handling code here:
        astro.homerMaxRadXY = ((Number)jFormattedTextFieldHomerRadXY.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldHomerRadXYPropertyChange

    private void jFormattedTextFieldHomerRadZPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHomerRadZPropertyChange
        // TODO add your handling code here:
        astro.homerMaxRadZ = ((Number)jFormattedTextFieldHomerRadZ.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldHomerRadZPropertyChange

    private void jFormattedTextFieldHomerNoisePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHomerNoisePropertyChange
        // TODO add your handling code here:
        astro.homerNoise = ((Number)jFormattedTextFieldHomerNoise.getValue()).intValue();
    }//GEN-LAST:event_jFormattedTextFieldHomerNoisePropertyChange

    private void jFormattedTextFieldHomerConfIntRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHomerConfIntRefActionPerformed
        // TODO add your handling code here:
        astro.homerConfDotsIntRef = ((Number)jFormattedTextFieldHomerConfIntRef.getValue()).intValue();

    }//GEN-LAST:event_jFormattedTextFieldHomerConfIntRefActionPerformed

    private void jFormattedTextFieldHomerConfIntRefPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHomerConfIntRefPropertyChange
        // TODO add your handling code here:
        astro.homerConfDotsIntRef = ((Number)jFormattedTextFieldHomerConfIntRef.getValue()).intValue();
    }//GEN-LAST:event_jFormattedTextFieldHomerConfIntRefPropertyChange

    private void jCheckBoxBleachHomerStedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBleachHomerStedActionPerformed
        // TODO add your handling code here:
        astro.bleachCorrHomerSted = jCheckBoxBleachAstro.isSelected();
    }//GEN-LAST:event_jCheckBoxBleachHomerStedActionPerformed

    private void jCheckBoxBleachHomerConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBleachHomerConfActionPerformed
        // TODO add your handling code here:
        astro.bleachCorrHomerConf = jCheckBoxBleachAstro.isSelected();
    }//GEN-LAST:event_jCheckBoxBleachHomerConfActionPerformed

    private void jCheckBoxBleachVglutStedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBleachVglutStedActionPerformed
        // TODO add your handling code here:
        astro.bleachCorrVglutSted = jCheckBoxBleachAstro.isSelected();
    }//GEN-LAST:event_jCheckBoxBleachVglutStedActionPerformed

    private void jCheckBoxBleachVglutConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBleachVglutConfActionPerformed
        // TODO add your handling code here:
        astro.bleachCorrVglutConf = jCheckBoxBleachAstro.isSelected();
        
    }//GEN-LAST:event_jCheckBoxBleachVglutConfActionPerformed

    private void jFormattedTextFieldMaxDistAstroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMaxDistAstroPropertyChange
        // TODO add your handling code here:
        astro.maxDistAstro = ((Number)jFormattedTextFieldMaxDistAstro.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldMaxDistAstroPropertyChange

    private void jFormattedTextFieldMaxDistAstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMaxDistAstroActionPerformed
        // TODO add your handling code here:
        astro.maxDistAstro = ((Number)jFormattedTextFieldMaxDistAstro.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldMaxDistAstroActionPerformed

    private void jFormattedTextFieldMaxDotsDistPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMaxDotsDistPropertyChange
        // TODO add your handling code here:
        astro.maxDistSynap = ((Number)jFormattedTextFieldMaxDotsDist.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldMaxDotsDistPropertyChange

    private void jFormattedTextFieldMaxDotsDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMaxDotsDistActionPerformed
        // TODO add your handling code here:
        astro.maxDistSynap = ((Number)jFormattedTextFieldMaxDotsDist.getValue()).floatValue();
    }//GEN-LAST:event_jFormattedTextFieldMaxDotsDistActionPerformed

    private void jCheckBoxBleachAstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBleachAstroActionPerformed
        // TODO add your handling code here:
        astro.bleachCorrAstro = jCheckBoxBleachAstro.isSelected();
    }//GEN-LAST:event_jCheckBoxBleachAstroActionPerformed

    /**
     * @param args the command line arguments
     */
//    public void main() {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SegmentationJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SegmentationJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SegmentationJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SegmentationJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                SegmentationJDialog dialog = new SegmentationJDialog(new javax.swing.JFrame(), true);
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JCheckBox jCheckBoxBleachAstro;
    private javax.swing.JCheckBox jCheckBoxBleachHomerConf;
    private javax.swing.JCheckBox jCheckBoxBleachHomerSted;
    private javax.swing.JCheckBox jCheckBoxBleachVglutConf;
    private javax.swing.JCheckBox jCheckBoxBleachVglutSted;
    private javax.swing.JComboBox jComboBoxAstroCh;
    private javax.swing.JComboBox jComboBoxHomerConfCh;
    private javax.swing.JComboBox jComboBoxHomerStedCh;
    private javax.swing.JComboBox jComboBoxVglutConfCh;
    private javax.swing.JComboBox jComboBoxVglutStedCh;
    private javax.swing.JFormattedTextField jFormattedTextFieldHomerConfIntRef;
    private javax.swing.JFormattedTextField jFormattedTextFieldHomerNoise;
    private javax.swing.JFormattedTextField jFormattedTextFieldHomerRadXY;
    private javax.swing.JFormattedTextField jFormattedTextFieldHomerRadZ;
    private javax.swing.JFormattedTextField jFormattedTextFieldMaxDistAstro;
    private javax.swing.JFormattedTextField jFormattedTextFieldMaxDotsDist;
    private javax.swing.JFormattedTextField jFormattedTextFieldVglutConfIntRef;
    private javax.swing.JFormattedTextField jFormattedTextFieldVglutNoise;
    private javax.swing.JFormattedTextField jFormattedTextFieldVglutRadXY;
    private javax.swing.JFormattedTextField jFormattedTextFieldVglutRadZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAstroBleach;
    private javax.swing.JLabel jLabelAstroCh;
    private javax.swing.JLabel jLabelHomerConfBleach;
    private javax.swing.JLabel jLabelHomerConfCh;
    private javax.swing.JLabel jLabelHomerMaxParams;
    private javax.swing.JLabel jLabelHomerNoise;
    private javax.swing.JLabel jLabelHomerParams;
    private javax.swing.JLabel jLabelHomerRadXY;
    private javax.swing.JLabel jLabelHomerRadZ;
    private javax.swing.JLabel jLabelHomerStedBleach;
    private javax.swing.JLabel jLabelHomerStedCh;
    private javax.swing.JLabel jLabelMaxDistAstro;
    private javax.swing.JLabel jLabelMaxDistSynap;
    private javax.swing.JLabel jLabelVglutConfBleach;
    private javax.swing.JLabel jLabelVglutConfh;
    private javax.swing.JLabel jLabelVglutNoise;
    private javax.swing.JLabel jLabelVglutParams;
    private javax.swing.JLabel jLabelVglutRadXY;
    private javax.swing.JLabel jLabelVglutRadZ;
    private javax.swing.JLabel jLabelVglutStedBleach;
    private javax.swing.JLabel jLabelVglutStedCh;
    private javax.swing.JLabel jLabelVglutrMaxParams;
    private javax.swing.JPanel jPanelChannels;
    private javax.swing.JPanel jPanelHomer;
    private javax.swing.JPanel jPanelSynapse;
    private javax.swing.JPanel jPanelVglut;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
